import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startBridge } from '../src/bridge.mjs';

test('real stdio client discovers and invokes review, comparison, browser capture and prompt', async t => {
  const data = mkdtempSync(join(tmpdir(), 'terms-mcp-'));
  const reservation = await startBridge({ token: 'b'.repeat(64), port: 0 });
  const port = reservation.server.address().port;
  await new Promise(resolve => reservation.server.close(resolve));
  const client = new Client({ name: 'terms-integration-test', version: '1.0.0' });
  const transport = new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../src/server.mjs', import.meta.url))], env: { ...process.env, TERMS_TLDR_DATA_DIR: data, TERMS_TLDR_BRIDGE_PORT: String(port) }, stderr: 'pipe' });
  t.after(() => client.close());
  await client.connect(transport);
  const names = (await client.listTools()).tools.map(t => t.name);
  assert.deepEqual(names.sort(), ['review_terms_text', 'review_terms_url', 'review_current_page', 'compare_terms_text', 'read_review_page'].sort());
  const result = await client.callTool({ name: 'review_terms_text', arguments: { text: 'You pay $12 per month. Cancel anytime.' } });
  assert.equal(result.structuredContent.document.clause_count, 1);
  const longText=Array.from({length:80},(_,i)=>`Section ${i}. ${'These fees renew annually. '.repeat(30)}`.trim()).join('\n\n');
  const long=await client.callTool({name:'review_terms_text',arguments:{text:longText}});
  assert.ok(long.structuredContent.pagination.total_pages>1);
  const full=[...long.structuredContent.source_clauses];
  for(let page=2;page<=long.structuredContent.pagination.total_pages;page++) {
    const next=await client.callTool({name:'read_review_page',arguments:{review_id:long.structuredContent.pagination.review_id,page}});
    assert.ok(!next.isError);
    full.push(...next.structuredContent.source_clauses);
  }
  assert.equal(full.map(c=>c.text).join('\n\n'),longText);
  const absent = await client.callTool({ name: 'review_current_page', arguments: {} });
  assert.equal(absent.isError, true);
  const pairing = JSON.parse(readFileSync(join(data, 'pairing.json'), 'utf8'));
  const capture = { url: 'https://example.com/terms', title: 'Fictional', text: 'You pay $12 per month.', links: [], captured_at: new Date().toISOString(), truncated: false, selection: false };
  const send = async value => {
    const response = await fetch(`${pairing.endpoint}/capture`, { method: 'POST', headers: { Authorization: `Bearer ${pairing.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(value) });
    assert.equal(response.status, 200);
  };
  await send(capture);
  assert.equal((await client.callTool({ name: 'review_current_page', arguments: {} })).structuredContent.changes.status, 'first_review');
  const second = new Client({ name: 'another-conversation', version: '1.0.0' });
  t.after(() => second.close());
  await second.connect(new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../src/server.mjs', import.meta.url))], env: { ...process.env, TERMS_TLDR_DATA_DIR: data, TERMS_TLDR_BRIDGE_PORT: String(port) }, stderr: 'pipe' }));
  const shared = await second.callTool({ name: 'review_current_page', arguments: {} });
  assert.ok(!shared.isError);
  assert.equal(shared.structuredContent.changes.status, 'unchanged');
  assert.equal(shared.structuredContent.source_clauses[0].text, capture.text);
  await send({ ...capture, text: 'You pay $24 per month.' });
  assert.equal((await client.callTool({ name: 'review_current_page', arguments: {} })).structuredContent.changes.status, 'text_changed');
  await send({ ...capture, text: 'partial', truncated: true });
  assert.equal((await client.callTool({ name: 'review_current_page', arguments: {} })).structuredContent.changes.status, 'comparison_skipped_partial_capture');
  await send({ ...capture, text: 'You pay $24 per month.' });
  assert.equal((await client.callTool({ name: 'review_current_page', arguments: {} })).structuredContent.changes.status, 'unchanged');
  const comparison = await client.callTool({ name: 'compare_terms_text', arguments: { before: '$12 per month', after: '$24 per month' } });
  assert.equal(comparison.structuredContent.changes.status, 'text_changed');
  const blocked = await client.callTool({ name: 'review_terms_url', arguments: { url: 'https://127.0.0.1' } });
  assert.equal(blocked.isError, true);
  const prompt = await client.getPrompt({ name: 'before_you_agree', arguments: {} });
  assert.match(prompt.messages[0].content.text, /review_current_page/);
});
