import { chromium } from 'playwright';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import http from 'node:http';

const root = fileURLToPath(new URL('../', import.meta.url));
const directory = mkdtempSync(join(tmpdir(), 'terms-browser-'));
const client = new Client({ name: 'real-browser-test', version: '1.0.0' });
const transport = new StdioClientTransport({ command: process.execPath, args: [join(root, 'src/server.mjs')], env: { ...process.env, TERMS_TLDR_DATA_DIR: directory }, stderr: 'inherit' });
const fixture = readFileSync(join(root, 'examples/fictional-terms.txt'), 'utf8');
const web = http.createServer((req, res) => res.end(`<html><head><title>Fictional CloudNotebook</title></head><body><h1>Fictional terms</h1><div style="white-space:pre-wrap">${fixture}</div><a href="https://example.com/terms">Terms of service</a><input type="password" value="FICTIONAL_SECRET_SHOULD_NOT_CAPTURE"></body></html>`));
await new Promise(resolve => web.listen(0, '127.0.0.1', resolve));
let context;
try {
  await client.connect(transport);
  const executablePath = process.env.BROWSER_EXECUTABLE || (process.platform === 'win32' ? 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' : undefined);
  context = await chromium.launchPersistentContext(join(directory, 'browser'), { executablePath, headless: true, ignoreDefaultArgs: ['--disable-extensions'], args: [`--disable-extensions-except=${join(root, 'extension')}`, `--load-extension=${join(root, 'extension')}`] });
  const management = await context.newPage();
  await management.goto('chrome://extensions');
  await management.getByText('Terms TLDR', { exact: true }).waitFor();
  await management.getByText('Details', { exact: true }).click();
  await management.waitForURL(/id=/);
  const id = new URL(management.url()).searchParams.get('id');
  assert.match(id, /^[a-p]{32}$/);
  const target = await context.newPage();
  await target.goto(`http://127.0.0.1:${web.address().port}/terms`);
  const popup = await context.newPage();
  await popup.goto(`chrome-extension://${id}/popup.html`);
  await popup.locator('summary').click();
  await popup.locator('#pair').setInputFiles(join(directory, 'pairing.json'));
  await popup.getByText('Connected settings saved.', { exact: false }).waitFor();
  await target.bringToFront();
  await popup.locator('#capture').click();
  await popup.getByText('Page captured.', { exact: false }).waitFor({ timeout: 10000 });
  const result = await client.callTool({ name: 'review_current_page', arguments: {} });
  assert.equal(result.isError, undefined);
  assert.equal(result.structuredContent.changes.status, 'first_review');
  assert.ok(result.structuredContent.source_clauses.some(c => c.text.includes('$12')));
  assert.ok(!JSON.stringify(result.structuredContent).includes('FICTIONAL_SECRET_SHOULD_NOT_CAPTURE'));
  assert.equal(result.structuredContent.browser_context.candidate_policy_links[0].url, 'https://example.com/terms');
  await target.locator('div').evaluate(el => { el.textContent = el.textContent.replace('$12', '$24'); });
  await target.bringToFront();
  await popup.locator('#capture').click();
  await popup.getByText('Page captured.', { exact: false }).waitFor();
  const updated = await client.callTool({ name: 'review_current_page', arguments: {} });
  assert.equal(updated.structuredContent.changes.status, 'text_changed');
  assert.ok(updated.structuredContent.changes.added.some(c => c.text.includes('$24')));
  assert.ok(updated.structuredContent.changes.removed.some(c => c.text.includes('$12')));
  await popup.setViewportSize({ width: 350, height: 730 });
  await popup.screenshot({ path: join(root, 'examples/extension-verified.png') });
  console.log(JSON.stringify({ extension_loaded: true, real_capture: true, mcp_review: true, first_baseline: true, changed_price_detected: true, password_value_excluded: true, terms_link_discovered: true }));
} finally { await context?.close(); await client.close(); await new Promise(resolve => web.close(resolve)); }
